server:
  port: 8081
  error:
    include-stacktrace: never
spring:
  application:
    name: member
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql
      mode: always
      continue-on-error: false
  data:
    redis:
      host: localhost
      port: 6379
      password:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      default.api.timeout.ms: 5000
logging:
  level:
    org.springframework.jdbc.core: TRACE


